# Copyright 2020-2021 Lowdefy, Inc

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_ref:
  path: templates/general.yaml.njk
  vars:
    pageId: tutorial-create-page-config
    pageTitle: Creating a page config
    section: Tutorial
    filePath: tutorial/tutorial-create-page-config.yaml
    content:
      - id: body_config
        type: MarkdownWithCode
        properties:
          content: |
            ##### `lowdefy.yaml`

            ```yaml
            name: lowdefy-project-template
            version: CURRENT_LOWDEFY_VERSION

            menus:
              - id: default
                links:
                  - id: new-ticket
                    type: MenuLink
                    properties:
                      icon: AiOutlinedAlert
                      title: New ticket
                    pageId: new-ticket
                  - id: welcome
                    type: MenuLink
                    properties:
                      icon: AiOutlinedHome
                      title: Home
                    pageId: welcome

            pages:
              - _ref: new-ticket.yaml
              - id: welcome
                type: PageHeaderMenu
                #...
            ```

            ##### `new-ticket.yaml`

            ```yaml
            id: new-ticket
            type: PageHeaderMenu
            properties:
              title: New ticket # The title in the browser tab.
            layout:
              contentJustify: center # Center the contents of the page.
            blocks:
              - id: content_card
                type: Card
                layout:
                  size: 800 # Set the size of the card so it does not fill the full screen.
                  contentGutter: 16 # Make a 16px gap between all blocks in this card.
                blocks:
                  - id: page_heading
                    type: Title
                    properties:
                      content: Log a ticket # The content text of the title block.
                      level: 3 # Make the title a little smaller (an html `<h3>`).
            ```
