name: Test Pull Requests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
        with: |
          git fetch --no-tags origin ${{ github.base_ref }}
          git checkout -b ${{ github.base_ref }}
          git checkout ${{ github.head_ref }}
      - name: Check yarn cache integrity
        run: yarn install --immutable --immutable-cache
      - name: Build packages
        run: yarn build

      # Make tests fail faster
      - name: Test changes since develop
        run: yarn test --ignore='@lowdefy/format' -- --changedSince=${{ github.base_ref }}
      # format tests don't pass on node 12 since icu is missing and tests don't work with locales
      - name: Test packages
        run: yarn test --ignore='@lowdefy/format'

      - name: Upload coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/*/coverage/lcov.info:lcov
